# Generated by Django 3.0.4 on 2020-04-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedentity',
            options={'verbose_name': 'Banned Entity', 'verbose_name_plural': 'Banned Entities'},
        ),
    ]
