# Generated by Django 3.1.1 on 2020-09-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannedentity',
            name='source',
        ),
        migrations.AddField(
            model_name='bannedentity',
            name='data_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='banned_entities', to='banned_list.datalist'),
            preserve_default=False,
        ),
    ]
