# Generated by Django 3.0.4 on 2020-04-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0002_auto_20200330_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BannedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('is_sanctioned', models.BooleanField()),
                ('extra_info', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Banned',
        ),
        migrations.AddField(
            model_name='alias',
            name='banned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='banned_list.BannedEntity'),
        ),
    ]
