# Generated by Django 3.1.1 on 2020-09-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0002_auto_20200917_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
    ]
