# Generated by Django 3.1.1 on 2020-09-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0003_parser_reusable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datalist',
            old_name='xml_file',
            new_name='parse_file',
        ),
    ]
