# Generated by Django 3.1.1 on 2020-09-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0007_database'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
                ('locking_token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banned_list.refreshtoken')),
            ],
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
