# Generated by Django 3.1.1 on 2020-10-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0008_auto_20200923_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalist',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banned_list.parser'),
        ),
    ]
