# Generated by Django 3.1.1 on 2020-10-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0009_auto_20201007_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
