# Generated by Django 3.1.1 on 2020-10-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banned_list', '0010_parser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalist',
            name='not_parsed',
            field=models.BooleanField(default=True),
        ),
    ]
